import { ArrowRight, HeartPulse, LockKeyhole, ShieldCheck } from 'lucide-react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { getApiErrorMessage } from '../services/api';

export default function Login() {
  const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(''); if (!form.email.trim() || !form.password) { setError('Enter your email and password to continue.'); return; } setLoading(true); try { await login(form); navigate(location.state?.from || '/dashboard', { replace: true }); } catch (requestError) { setError(getApiErrorMessage(requestError, 'Email or password is incorrect.')); } finally { setLoading(false); } };
  return <AuthLayout title="Welcome back" subtitle="Sign in to continue your private health journey."><form className="auth-form" onSubmit={submit}><Field label="Email address" type="email" value={form.email} onChange={(value) => setForm({ ...form, email: value })} placeholder="you@example.com" /><Field label="Password" type="password" value={form.password} onChange={(value) => setForm({ ...form, password: value })} placeholder="Enter your password" /><p className="auth-switch auth-forgot"><Link to="/forgot-password">Forgot password?</Link></p>{error && <div className="form-error">{error}</div>}<button className="btn btn-primary auth-submit" disabled={loading}>{loading ? 'Signing in...' : 'Sign in'} <ArrowRight size={17} /></button><p className="auth-switch">New to CardioGuard? <Link to="/signup">Create an account</Link></p></form></AuthLayout>;
}

export function AuthLayout({ title, subtitle, children }) { return <div className="auth-page"><Link to="/" className="auth-brand"><span className="brand-icon"><HeartPulse size={19} /></span><span className="brand-copy"><strong>Cardio<span>Guard</span></strong><small>AI health intelligence</small></span></Link><div className="auth-layout"><div className="auth-intro"><span className="eyebrow"><ShieldCheck size={14} /> Private health workspace</span><h1>Clarity for the<br /><em>conversation ahead.</em></h1><p>Your health data stays connected to your account, so your insights are ready when you are.</p></div><section className="auth-card"><div className="auth-card-head"><span className="auth-lock"><LockKeyhole size={17} /></span><div><h2>{title}</h2><p>{subtitle}</p></div></div>{children}</section></div><footer className="auth-footer">CardioGuard AI · Educational tool, not a diagnosis</footer></div>; }
function Field({ label, type, value, onChange, placeholder }) { return <label className="auth-field"><span>{label}</span><input required type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label>; }