import { ArrowRight, Check, LockKeyhole } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { AuthLayout } from './Login';
import { useAuth } from '../context/AuthContext';
import { getApiErrorMessage } from '../services/api';

export default function Signup() {
  const { signup } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '', confirm_password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const update = (key, value) => setForm({ ...form, [key]: value });
  const submit = async (event) => { event.preventDefault(); setError(''); if (form.password.length < 8) { setError('Password must be at least 8 characters.'); return; } if (form.password !== form.confirm_password) { setError('Passwords do not match.'); return; } setLoading(true); try { await signup({ ...form, name: form.name.trim(), email: form.email.trim().toLowerCase() }); navigate('/dashboard', { replace: true }); } catch (requestError) { setError(getApiErrorMessage(requestError, 'Unable to create your account right now.')); } finally { setLoading(false); } };
  return <AuthLayout title="Create your account" subtitle="Start a private, personalized health workspace."><form className="auth-form" onSubmit={submit}><label className="auth-field"><span>Full name</span><input required minLength="2" value={form.name} onChange={(event) => update('name', event.target.value)} placeholder="Your name" /></label><label className="auth-field"><span>Email address</span><input required type="email" value={form.email} onChange={(event) => update('email', event.target.value)} placeholder="you@example.com" /></label><div className="auth-two-fields"><label className="auth-field"><span>Password</span><input required minLength="8" type="password" value={form.password} onChange={(event) => update('password', event.target.value)} placeholder="8+ characters" /></label><label className="auth-field"><span>Confirm password</span><input required minLength="8" type="password" value={form.confirm_password} onChange={(event) => update('confirm_password', event.target.value)} placeholder="Repeat password" /></label></div><div className="password-note"><Check size={14} /> Use at least 8 characters</div>{error && <div className="form-error">{error}</div>}<button className="btn btn-primary auth-submit" disabled={loading}>{loading ? 'Creating account...' : 'Create account'} <ArrowRight size={17} /></button><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p><p className="auth-legal"><LockKeyhole size={13} /> Your account protects access to your health data.</p></form></AuthLayout>;
}